// Daily travel budget (USD) per country — backpacker average
export const BUDGET_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Thailand', budget: 35, tier: 'Budget 🟢', range: '$25–$55/day', tourists: 40 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Japan', budget: 120, tier: 'Mid-Range 🟡', range: '$90–$180/day', tourists: 32 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', budget: 45, tier: 'Budget 🟢', range: '$30–$70/day', tourists: 17 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Vietnam', budget: 28, tier: 'Budget 🟢', range: '$20–$45/day', tourists: 18 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Portugal', budget: 72, tier: 'Mid-Range 🟡', range: '$55–$110/day', tourists: 21 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', budget: 165, tier: 'Expensive 🔴', range: '$120–$250/day', tourists: 19 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.07, 4.71] }, properties: { name: 'Colombia', budget: 38, tier: 'Budget 🟢', range: '$25–$60/day', tourists: 5 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-21.93, 64.13] }, properties: { name: 'Iceland', budget: 210, tier: 'Very Expensive 💸', range: '$160–$300/day', tourists: 2 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-3.70, 40.42] }, properties: { name: 'Spain', budget: 82, tier: 'Mid-Range 🟡', range: '$60–$120/day', tourists: 84 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [12.50, 41.90] }, properties: { name: 'Italy', budget: 95, tier: 'Mid-Range 🟡', range: '$70–$140/day', tourists: 94 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [23.73, 37.98] }, properties: { name: 'Greece', budget: 62, tier: 'Mid-Range 🟡', range: '$45–$95/day', tourists: 32 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.35, 48.86] }, properties: { name: 'France', budget: 130, tier: 'Expensive 🔴', range: '$100–$200/day', tourists: 90 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-0.13, 51.51] }, properties: { name: 'UK', budget: 155, tier: 'Expensive 🔴', range: '$120–$220/day', tourists: 38 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.01, 40.71] }, properties: { name: 'New York', budget: 180, tier: 'Expensive 🔴', range: '$130–$270/day', tourists: 66 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Australia', budget: 145, tier: 'Expensive 🔴', range: '$110–$210/day', tourists: 9 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [174.76, -36.85] }, properties: { name: 'New Zealand', budget: 125, tier: 'Expensive 🔴', range: '$90–$180/day', tourists: 4 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-7.98, 31.63] }, properties: { name: 'Morocco', budget: 42, tier: 'Budget 🟢', range: '$30–$65/day', tourists: 13 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [36.82, -1.29] }, properties: { name: 'Kenya', budget: 75, tier: 'Mid-Range 🟡', range: '$50–$120/day', tourists: 2 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.04, -12.05] }, properties: { name: 'Peru', budget: 40, tier: 'Budget 🟢', range: '$28–$65/day', tourists: 4 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-99.13, 19.43] }, properties: { name: 'Mexico', budget: 48, tier: 'Budget 🟢', range: '$35–$75/day', tourists: 45 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Brazil', budget: 55, tier: 'Mid-Range 🟡', range: '$40–$85/day', tourists: 6 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [72.88, 19.08] }, properties: { name: 'India', budget: 25, tier: 'Ultra Budget 💚', range: '$15–$40/day', tourists: 17 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', budget: 135, tier: 'Expensive 🔴', range: '$100–$220/day', tourists: 16 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-79.38, 43.65] }, properties: { name: 'Canada', budget: 130, tier: 'Expensive 🔴', range: '$100–$190/day', tourists: 22 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Germany', budget: 88, tier: 'Mid-Range 🟡', range: '$65–$130/day', tourists: 38 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [4.90, 52.37] }, properties: { name: 'Amsterdam', budget: 105, tier: 'Expensive 🔴', range: '$80–$160/day', tourists: 22 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [14.42, 50.09] }, properties: { name: 'Prague', budget: 52, tier: 'Budget 🟢', range: '$38–$80/day', tourists: 8 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.09, 42.65] }, properties: { name: 'Croatia', budget: 60, tier: 'Mid-Range 🟡', range: '$45–$90/day', tourists: 20 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.98, 41.01] }, properties: { name: 'Istanbul', budget: 50, tier: 'Budget 🟢', range: '$35–$80/day', tourists: 13 } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.42, -33.92] }, properties: { name: 'Cape Town', budget: 58, tier: 'Mid-Range 🟡', range: '$42–$90/day', tourists: 3 } },
    ],
};
