/* trendingData — Static GeoJSON data for the trending map overlay layer. */
export const TRENDING_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Bangkok', trend: '+34%', rank: 1, searches: 2.8, reason: 'Street food & temples', momentum: 'Rising', tag: '🔥 Viral' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Tokyo', trend: '+28%', rank: 2, searches: 3.1, reason: 'Cherry blossom season', momentum: 'Peak', tag: '🌸 Seasonal' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.07, 4.71] }, properties: { name: 'Medellín', trend: '+52%', rank: 3, searches: 1.9, reason: 'Tech hub + digital nomads', momentum: 'Surging', tag: '🚀 Breakout' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Lisbon', trend: '+19%', rank: 4, searches: 2.2, reason: 'Golden visa & digital nomads', momentum: 'Steady', tag: '💻 Nomad Hub' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [25.15, 36.85] }, properties: { name: 'Santorini', trend: '+41%', rank: 5, searches: 2.5, reason: 'Instagram hotspot', momentum: 'Rising', tag: '📸 Instagrammable' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [119.89, 10.54] }, properties: { name: 'Palawan', trend: '+67%', rank: 6, searches: 1.4, reason: 'Ranked worlds best island', momentum: 'Surging', tag: '🏝️ Hidden Gem' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-21.93, 64.13] }, properties: { name: 'Reykjavik', trend: '+22%', rank: 7, searches: 1.8, reason: 'Northern lights season', momentum: 'Seasonal', tag: '🌌 Aurora Season' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', trend: '+15%', rank: 8, searches: 3.4, reason: 'Expo aftermath & luxury tourism', momentum: 'Steady', tag: '✨ Luxury' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [126.98, 37.57] }, properties: { name: 'Seoul', trend: '+44%', rank: 9, searches: 2.1, reason: 'K-culture & food scene explosion', momentum: 'Surging', tag: '🎵 K-Wave' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', trend: '+12%', rank: 10, searches: 2.0, reason: 'Business + leisure hub', momentum: 'Stable', tag: '🌆 Business' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.04, -12.05] }, properties: { name: 'Lima', trend: '+38%', rank: 11, searches: 1.3, reason: 'World-class food scene', momentum: 'Rising', tag: '🍽️ Food Capital' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [36.82, -1.29] }, properties: { name: 'Nairobi', trend: '+29%', rank: 12, searches: 1.1, reason: 'Safari + tech scene growing', momentum: 'Rising', tag: '🦁 Safari' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Berlin', trend: '+8%', rank: 13, searches: 1.9, reason: 'Art & culture renaissance', momentum: 'Stable', tag: '🎨 Culture' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', trend: '+31%', rank: 14, searches: 2.7, reason: 'Post-COVID recovery peak', momentum: 'Rising', tag: '🌺 Comeback' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio de Janeiro', trend: '+23%', rank: 15, searches: 1.6, reason: 'Carnaval & Olympic legacy', momentum: 'Seasonal', tag: '🎭 Carnaval' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Sydney', trend: '+17%', rank: 16, searches: 1.8, reason: 'Southern hemisphere summer', momentum: 'Seasonal', tag: '☀️ Summer' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.09, 42.65] }, properties: { name: 'Dubrovnik', trend: '+45%', rank: 17, searches: 1.5, reason: 'Game of Thrones tourism', momentum: 'Rising', tag: '🏰 Film Location' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-7.98, 31.63] }, properties: { name: 'Marrakech', trend: '+33%', rank: 18, searches: 1.7, reason: 'Luxury riad experiences', momentum: 'Rising', tag: '🕌 Exotic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [172.47, -43.73] }, properties: { name: 'Queenstown', trend: '+26%', rank: 19, searches: 1.2, reason: 'Adventure travel boom', momentum: 'Rising', tag: '🎿 Adventure' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Hanoi', trend: '+21%', rank: 20, searches: 1.4, reason: 'Budget travel discovery', momentum: 'Steady', tag: '🌏 Budget Pick' } },
    ],
};
