// Safety scores (0–100) and travel advisory levels per destination
export const SAFETY_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Thailand', score: 74, level: 'Exercise Caution', advisory: 'Low crime. Watch for scams.', color: '#eab308' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Japan', score: 98, level: 'Very Safe', advisory: 'One of the world\'s safest countries.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', score: 73, level: 'Exercise Caution', advisory: 'Generally safe. Petty theft in tourist areas.', color: '#eab308' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Vietnam', score: 78, level: 'Safe', advisory: 'Low violent crime. Traffic risk.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Portugal', score: 89, level: 'Very Safe', advisory: 'One of Europe\'s safest countries.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', score: 97, level: 'Very Safe', advisory: 'Extremely low crime. Strict laws.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.07, 4.71] }, properties: { name: 'Colombia', score: 55, level: 'High Caution', advisory: 'Improving rapidly. Avoid certain zones.', color: '#f97316' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-21.93, 64.13] }, properties: { name: 'Iceland', score: 99, level: 'Very Safe', advisory: 'World\'s most peaceful country.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-3.70, 40.42] }, properties: { name: 'Spain', score: 87, level: 'Safe', advisory: 'Safe for tourists. Watch pickpockets in cities.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [12.50, 41.90] }, properties: { name: 'Italy', score: 82, level: 'Safe', advisory: 'Safe overall. Pickpockets in tourist areas.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [23.73, 37.98] }, properties: { name: 'Greece', score: 85, level: 'Safe', advisory: 'Very tourist-friendly. Low violent crime.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.35, 48.86] }, properties: { name: 'France', score: 79, level: 'Safe', advisory: 'Generally safe. Terrorism risk awareness.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-0.13, 51.51] }, properties: { name: 'UK', score: 82, level: 'Safe', advisory: 'Safe but be aware in late night situations.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.01, 40.71] }, properties: { name: 'New York', score: 72, level: 'Exercise Caution', advisory: 'Safe in tourist areas. Vary by neighborhood.', color: '#eab308' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Australia', score: 93, level: 'Very Safe', advisory: 'Excellent safety. Wildlife awareness needed.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [174.76, -36.85] }, properties: { name: 'New Zealand', score: 96, level: 'Very Safe', advisory: 'One of the world\'s safest destinations.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-7.98, 31.63] }, properties: { name: 'Morocco', score: 67, level: 'Exercise Caution', advisory: 'Safe in tourist areas. Watch haggling scams.', color: '#f97316' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [36.82, -1.29] }, properties: { name: 'Kenya', score: 54, level: 'High Caution', advisory: 'Regional risk variation. Avoid certain areas.', color: '#ef4444' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.04, -12.05] }, properties: { name: 'Peru', score: 60, level: 'Exercise Caution', advisory: 'Rising. Political instability in remote areas.', color: '#f97316' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-99.13, 19.43] }, properties: { name: 'Mexico', score: 52, level: 'High Caution', advisory: 'Tourist zones generally safe. Avoid northern states.', color: '#ef4444' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio de Janeiro', score: 48, level: 'High Caution', advisory: 'Beautiful city, elevated crime in certain areas.', color: '#ef4444' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [72.88, 19.08] }, properties: { name: 'India', score: 65, level: 'Exercise Caution', advisory: 'Varies by region. Major cities generally ok.', color: '#f97316' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', score: 94, level: 'Very Safe', advisory: 'Very safe. Strict local laws apply.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-79.38, 43.65] }, properties: { name: 'Canada', score: 92, level: 'Very Safe', advisory: 'Excellent safety record across all regions.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Germany', score: 89, level: 'Very Safe', advisory: 'Very safe and well-structured infrastructure.', color: '#10b981' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [4.90, 52.37] }, properties: { name: 'Amsterdam', score: 88, level: 'Very Safe', advisory: 'Safe city. Bike theft common.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [14.42, 50.09] }, properties: { name: 'Prague', score: 86, level: 'Safe', advisory: 'Very safe for tourists. Tourist scams exist.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.09, 42.65] }, properties: { name: 'Dubrovnik', score: 88, level: 'Safe', advisory: 'Very safe coastal city. Low crime.', color: '#22c55e' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.98, 41.01] }, properties: { name: 'Istanbul', score: 70, level: 'Exercise Caution', advisory: 'Tourist areas safe. Be aware of surroundings.', color: '#eab308' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.42, -33.92] }, properties: { name: 'Cape Town', score: 46, level: 'High Caution', advisory: 'High inequality drives crime. Careful after dark.', color: '#ef4444' } },
    ],
};
