export const NOMAD_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Bangkok', country: 'Thailand', nomad_score: 88, cost: 1200, internet: 80, coworking: 95, community: 90, timezone: 'UTC+7' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-8.61, 39.40] }, properties: { name: 'Lisbon', country: 'Portugal', nomad_score: 94, cost: 2200, internet: 88, coworking: 97, community: 95, timezone: 'UTC+0' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.06, -26.21] }, properties: { name: 'Johannesburg', country: 'South Africa', nomad_score: 72, cost: 1100, internet: 70, coworking: 75, community: 70, timezone: 'UTC+2' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', country: 'Singapore', nomad_score: 89, cost: 4500, internet: 98, coworking: 95, community: 87, timezone: 'UTC+8' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-99.13, 19.43] }, properties: { name: 'Mexico City', country: 'Mexico', nomad_score: 87, cost: 1800, internet: 82, coworking: 92, community: 93, timezone: 'UTC-6' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.07, 4.71] }, properties: { name: 'Medellín', country: 'Colombia', nomad_score: 91, cost: 1400, internet: 85, coworking: 93, community: 95, timezone: 'UTC-5' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Hanoi', country: 'Vietnam', nomad_score: 84, cost: 900, internet: 78, coworking: 82, community: 80, timezone: 'UTC+7' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [35.21, 31.77] }, properties: { name: 'Tel Aviv', country: 'Israel', nomad_score: 88, cost: 3800, internet: 92, coworking: 90, community: 88, timezone: 'UTC+2' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [36.82, -1.29] }, properties: { name: 'Nairobi', country: 'Kenya', nomad_score: 76, cost: 1500, internet: 72, coworking: 80, community: 79, timezone: 'UTC+3' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Tokyo', country: 'Japan', nomad_score: 85, cost: 3200, internet: 97, coworking: 92, community: 82, timezone: 'UTC+9' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali (Canggu)', country: 'Indonesia', nomad_score: 92, cost: 1600, internet: 80, coworking: 96, community: 98, timezone: 'UTC+8' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-73.94, 40.65] }, properties: { name: 'New York', country: 'USA', nomad_score: 83, cost: 5000, internet: 95, coworking: 98, community: 88, timezone: 'UTC-5' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', country: 'UAE', nomad_score: 86, cost: 4000, internet: 94, coworking: 90, community: 85, timezone: 'UTC+4' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.35, 48.86] }, properties: { name: 'Paris', country: 'France', nomad_score: 79, cost: 3500, internet: 87, coworking: 90, community: 82, timezone: 'UTC+1' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio de Janeiro', country: 'Brazil', nomad_score: 80, cost: 2000, internet: 78, coworking: 82, community: 88, timezone: 'UTC-3' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Sydney', country: 'Australia', nomad_score: 84, cost: 4200, internet: 90, coworking: 92, community: 85, timezone: 'UTC+11' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Lisbon (Alt)', country: 'Portugal', nomad_score: 93, cost: 2100, internet: 87, coworking: 96, community: 94, timezone: 'UTC+1' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [106.68, 10.76] }, properties: { name: 'Ho Chi Minh City', country: 'Vietnam', nomad_score: 86, cost: 1100, internet: 82, coworking: 88, community: 87, timezone: 'UTC+7' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [121.47, 31.23] }, properties: { name: 'Shanghai', country: 'China', nomad_score: 78, cost: 2800, internet: 88, coworking: 88, community: 75, timezone: 'UTC+8' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Berlin', country: 'Germany', nomad_score: 88, cost: 2800, internet: 88, coworking: 94, community: 92, timezone: 'UTC+1' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [126.98, 37.57] }, properties: { name: 'Seoul', country: 'South Korea', nomad_score: 87, cost: 2600, internet: 99, coworking: 92, community: 84, timezone: 'UTC+9' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [32.87, 39.92] }, properties: { name: 'Ankara', country: 'Turkey', nomad_score: 74, cost: 1500, internet: 80, coworking: 75, community: 72, timezone: 'UTC+3' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-64.72, 32.30] }, properties: { name: 'Bermuda', country: 'Bermuda', nomad_score: 82, cost: 5200, internet: 89, coworking: 78, community: 80, timezone: 'UTC-4' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.03, 38.90] }, properties: { name: 'Washington DC', country: 'USA', nomad_score: 81, cost: 4500, internet: 93, coworking: 94, community: 85, timezone: 'UTC-5' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.42, -33.92] }, properties: { name: 'Cape Town', country: 'South Africa', nomad_score: 85, cost: 1800, internet: 79, coworking: 86, community: 88, timezone: 'UTC+2' } },
    ],
};
