export const BEACH_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.06, 9.53] }, properties: { name: 'Koh Samui', country: 'Thailand', water: 'Crystal Clear', rating: 9.4, crowd: 'Moderate', best: 'Dec–Apr', type: 'Island' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.17, -8.73] }, properties: { name: 'Seminyak', country: 'Bali', water: 'Warm', rating: 9.1, crowd: 'Busy', best: 'Apr–Oct', type: 'Surf' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [98.30, 7.88] }, properties: { name: 'Phi Phi Islands', country: 'Thailand', water: 'Turquoise', rating: 9.7, crowd: 'Moderate', best: 'Nov–Apr', type: 'Secluded' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [119.89, 10.54] }, properties: { name: 'Palawan', country: 'Philippines', water: 'Crystal Clear', rating: 9.9, crowd: 'Quiet', best: 'Nov–May', type: 'Pristine' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [73.53, 4.17] }, properties: { name: 'Maldives', country: 'Maldives', water: 'Turquoise', rating: 9.8, crowd: 'Quiet', best: 'Nov–Apr', type: 'Luxury' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.54, -4.62] }, properties: { name: 'Seychelles', country: 'Seychelles', water: 'Crystal Clear', rating: 9.8, crowd: 'Quiet', best: 'Apr–May, Oct–Nov', type: 'Luxury' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-81.79, 24.56] }, properties: { name: 'Key West', country: 'USA', water: 'Warm', rating: 8.9, crowd: 'Moderate', best: 'Mar–May', type: 'Classic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-61.73, 15.30] }, properties: { name: 'Martinique', country: 'Caribbean', water: 'Caribbean Blue', rating: 9.3, crowd: 'Quiet', best: 'Dec–May', type: 'Tropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-149.83, -17.65] }, properties: { name: 'Bora Bora', country: 'French Polynesia', water: 'Lagoon Blue', rating: 9.9, crowd: 'Quiet', best: 'May–Oct', type: 'Luxury' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [39.20, -6.17] }, properties: { name: 'Zanzibar', country: 'Tanzania', water: 'Turquoise', rating: 9.5, crowd: 'Moderate', best: 'Jun–Oct', type: 'Island' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.28, -23.85] }, properties: { name: 'Whitsundays', country: 'Australia', water: 'Clear', rating: 9.6, crowd: 'Moderate', best: 'Jun–Oct', type: 'Tropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-16.91, 14.63] }, properties: { name: 'Cap Skirring', country: 'Senegal', water: 'Atlantic', rating: 8.7, crowd: 'Quiet', best: 'Nov–May', type: 'Surf' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-28.64, 38.53] }, properties: { name: 'Azores', country: 'Portugal', water: 'Atlantic', rating: 9.2, crowd: 'Quiet', best: 'Jun–Sep', type: 'Wild' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [9.00, 40.05] }, properties: { name: 'Sardinia', country: 'Italy', water: 'Mediterranean', rating: 9.4, crowd: 'Moderate', best: 'Jun–Sep', type: 'Classic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [25.15, 36.85] }, properties: { name: 'Santorini', country: 'Greece', water: 'Aegean', rating: 9.3, crowd: 'Busy', best: 'May–Oct', type: 'Volcanic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-17.07, 32.64] }, properties: { name: 'Madeira', country: 'Portugal', water: 'Atlantic', rating: 8.9, crowd: 'Quiet', best: 'Apr–Oct', type: 'Natural' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.18, -22.98] }, properties: { name: 'Ipanema', country: 'Brazil', water: 'Atlantic', rating: 9.2, crowd: 'Busy', best: 'Nov–Apr', type: 'Urban' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [106.14, 10.40] }, properties: { name: 'Phu Quoc', country: 'Vietnam', water: 'Gulf of Thailand', rating: 9.3, crowd: 'Moderate', best: 'Nov–Apr', type: 'Island' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [157.95, -8.50] }, properties: { name: 'Solomon Islands', country: 'Pacific', water: 'Crystal Clear', rating: 9.5, crowd: 'Quiet', best: 'Apr–Nov', type: 'Pristine' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-70.02, 12.52] }, properties: { name: 'Aruba', country: 'Caribbean', water: 'Caribbean Blue', rating: 9.4, crowd: 'Moderate', best: 'Year-round', type: 'Classic' } },
    ],
};
