/* foodData — Static GeoJSON data for the food map overlay layer. */
export const FOOD_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Tokyo', cuisine: 'Japanese', signature: 'Ramen & Sushi', michelin: 3, rating: 9.8, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Bangkok', cuisine: 'Thai', signature: 'Pad Thai & Tom Yum', michelin: 1, rating: 9.5, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.35, 48.86] }, properties: { name: 'Paris', cuisine: 'French', signature: 'Croissant & Boeuf Bourguignon', michelin: 3, rating: 9.7, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', cuisine: 'Fusion Asian', signature: 'Chilli Crab & Laksa', michelin: 2, rating: 9.6, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [12.50, 41.90] }, properties: { name: 'Rome', cuisine: 'Italian', signature: 'Carbonara & Cacio e Pepe', michelin: 2, rating: 9.5, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio de Janeiro', cuisine: 'Brazilian', signature: 'Churrasco & Feijoada', michelin: 1, rating: 8.8, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [121.47, 31.23] }, properties: { name: 'Shanghai', cuisine: 'Chinese', signature: 'Xiaolongbao & Peking Duck', michelin: 2, rating: 9.4, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-99.13, 19.43] }, properties: { name: 'Mexico City', cuisine: 'Mexican', signature: 'Tacos al Pastor & Mole', michelin: 1, rating: 9.3, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.98, 41.01] }, properties: { name: 'Istanbul', cuisine: 'Turkish', signature: 'Kebab & Baklava', michelin: 1, rating: 9.1, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', cuisine: 'Emirati/Fusion', signature: 'Al Harees & Shawarma', michelin: 2, rating: 8.9, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [72.88, 19.08] }, properties: { name: 'Mumbai', cuisine: 'Indian', signature: 'Vada Pav & Butter Chicken', michelin: 1, rating: 9.2, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.42, -33.92] }, properties: { name: 'Cape Town', cuisine: 'South African', signature: 'Braai & Bobotie', michelin: 1, rating: 8.7, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-0.13, 51.51] }, properties: { name: 'London', cuisine: 'Modern British', signature: 'Fish & Chips & Sunday Roast', michelin: 2, rating: 8.8, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.01, 40.71] }, properties: { name: 'New York', cuisine: 'American/Fusion', signature: 'Pizza & Bagels', michelin: 3, rating: 9.4, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Hanoi', cuisine: 'Vietnamese', signature: 'Pho & Bun Cha', michelin: 1, rating: 9.3, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', cuisine: 'Balinese', signature: 'Babi Guling & Nasi Campur', michelin: 0, rating: 8.9, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-7.98, 31.63] }, properties: { name: 'Marrakech', cuisine: 'Moroccan', signature: 'Tagine & Couscous', michelin: 0, rating: 9.0, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [23.73, 37.98] }, properties: { name: 'Athens', cuisine: 'Greek', signature: 'Souvlaki & Moussaka', michelin: 1, rating: 9.1, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.04, -12.05] }, properties: { name: 'Lima', cuisine: 'Peruvian', signature: 'Ceviche & Lomo Saltado', michelin: 2, rating: 9.5, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Sydney', cuisine: 'Modern Australian', signature: 'Barramundi & Meat Pie', michelin: 1, rating: 8.8, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [4.90, 52.37] }, properties: { name: 'Amsterdam', cuisine: 'Dutch/International', signature: 'Stroopwafel & Haring', michelin: 2, rating: 8.7, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Lisbon', cuisine: 'Portuguese', signature: 'Pastel de Nata & Bacalhau', michelin: 1, rating: 9.2, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [126.98, 37.57] }, properties: { name: 'Seoul', cuisine: 'Korean', signature: 'Bibimbap & Korean BBQ', michelin: 2, rating: 9.4, vegan: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [77.21, 28.61] }, properties: { name: 'Delhi', cuisine: 'North Indian', signature: 'Butter Naan & Chaat', michelin: 0, rating: 9.1, vegan: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Berlin', cuisine: 'German/International', signature: 'Currywurst & Pretzels', michelin: 1, rating: 8.6, vegan: true } },
    ],
};
