export const NIGHTLIFE_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.17, 41.38] }, properties: { name: 'Barcelona', scene: 'Club & Beach Party', vibe: 'Energetic', rating: 9.7, budget: 'Mid', opens: '12am', closes: '7am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Berlin', scene: 'Techno Underground', vibe: 'Intense', rating: 9.9, budget: 'Budget', opens: '12am', closes: 'Never' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [114.15, 22.28] }, properties: { name: 'Hong Kong', scene: 'Rooftop Bars', vibe: 'Glamorous', rating: 9.3, budget: 'Expensive', opens: '9pm', closes: '4am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.01, 40.71] }, properties: { name: 'New York', scene: 'Jazz & Rooftop', vibe: 'Diverse', rating: 9.4, budget: 'Expensive', opens: '10pm', closes: '4am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Bangkok', scene: 'Sky Bars & Night Markets', vibe: 'Wild', rating: 9.5, budget: 'Budget', opens: '6pm', closes: '2am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [144.96, -37.82] }, properties: { name: 'Melbourne', scene: 'Live Music & Laneways', vibe: 'Eclectic', rating: 9.2, budget: 'Mid', opens: '8pm', closes: '3am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio de Janeiro', scene: 'Samba & Carnaval', vibe: 'Electric', rating: 9.6, budget: 'Budget', opens: '10pm', closes: 'Dawn' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-3.70, 40.42] }, properties: { name: 'Madrid', scene: 'Tapas & Late-night Clubs', vibe: 'Festive', rating: 9.3, budget: 'Mid', opens: '11pm', closes: '6am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', scene: 'Clarke Quay & Marina', vibe: 'Sophisticated', rating: 8.9, budget: 'Expensive', opens: '9pm', closes: '3am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', scene: 'Luxury Rooftop Lounges', vibe: 'Opulent', rating: 9.0, budget: 'Luxury', opens: '9pm', closes: '3am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-0.13, 51.51] }, properties: { name: 'London', scene: 'Pub Culture & Shoreditch', vibe: 'Creative', rating: 9.1, budget: 'Mid', opens: '8pm', closes: '3am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.98, 41.01] }, properties: { name: 'Istanbul', scene: 'Bosphorus Nightclubs', vibe: 'Vibrant', rating: 9.0, budget: 'Mid', opens: '11pm', closes: '5am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [126.98, 37.57] }, properties: { name: 'Seoul', scene: 'Hongdae K-Pop Clubs', vibe: 'Trendy', rating: 9.4, budget: 'Mid', opens: '10pm', closes: '5am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Tokyo', scene: 'Shinjuku Izakayas & Clubs', vibe: 'Unique', rating: 9.3, budget: 'Mid', opens: '7pm', closes: '5am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', scene: 'Seminyak Beach Clubs', vibe: 'Tropical', rating: 9.1, budget: 'Budget', opens: '6pm', closes: '4am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [4.90, 52.37] }, properties: { name: 'Amsterdam', scene: 'Canals & Techno Clubs', vibe: 'Free-spirited', rating: 9.2, budget: 'Mid', opens: '11pm', closes: '6am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [23.73, 37.98] }, properties: { name: 'Athens', scene: 'Rooftop Bars & Beach Clubs', vibe: 'Elegant', rating: 9.0, budget: 'Mid', opens: '10pm', closes: '5am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-80.14, 25.78] }, properties: { name: 'Miami', scene: 'South Beach & EDM', vibe: 'Glamorous', rating: 9.4, budget: 'Expensive', opens: '11pm', closes: '5am' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-115.17, 36.12] }, properties: { name: 'Las Vegas', scene: 'Casino & Mega Clubs', vibe: 'Over-the-top', rating: 9.6, budget: 'Expensive', opens: '9pm', closes: 'Never' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [121.47, 31.23] }, properties: { name: 'Shanghai', scene: 'The Bund & Rooftop Scene', vibe: 'Cosmopolitan', rating: 9.2, budget: 'Mid', opens: '9pm', closes: '4am' } },
    ],
};
