// Average temperature (°C) and weather condition for major cities
export const WEATHER_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Bangkok', temp: 34, condition: 'Sunny ☀️', humidity: 78, best: 'Nov–Feb', season: 'Hot' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Tokyo', temp: 16, condition: 'Mild 🌤️', humidity: 60, best: 'Mar–May, Sep–Nov', season: 'Temperate' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', temp: 30, condition: 'Sunny ☀️', humidity: 82, best: 'Apr–Oct', season: 'Tropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Hanoi', temp: 24, condition: 'Warm 🌤️', humidity: 70, best: 'Oct–Apr', season: 'Subtropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Lisbon', temp: 18, condition: 'Pleasant 🌤️', humidity: 58, best: 'Apr–Oct', season: 'Mediterranean' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', temp: 32, condition: 'Hot & Humid 🌊', humidity: 84, best: 'Feb–Apr', season: 'Tropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.07, 4.71] }, properties: { name: 'Bogotá', temp: 14, condition: 'Cool 🌥️', humidity: 65, best: 'Dec–Mar, Jul–Aug', season: 'Highland' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-21.93, 64.13] }, properties: { name: 'Reykjavik', temp: 2, condition: 'Cold ❄️', humidity: 75, best: 'Jun–Aug', season: 'Arctic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-3.70, 40.42] }, properties: { name: 'Madrid', temp: 16, condition: 'Sunny ☀️', humidity: 45, best: 'Apr–Jun, Sep–Oct', season: 'Mediterranean' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [12.50, 41.90] }, properties: { name: 'Rome', temp: 20, condition: 'Sunny ☀️', humidity: 55, best: 'Apr–Jun, Sep–Oct', season: 'Mediterranean' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [23.73, 37.98] }, properties: { name: 'Athens', temp: 22, condition: 'Sunny ☀️', humidity: 50, best: 'Apr–Jun, Sep–Oct', season: 'Mediterranean' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.35, 48.86] }, properties: { name: 'Paris', temp: 12, condition: 'Cloudy 🌥️', humidity: 75, best: 'Jun–Aug', season: 'Temperate' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-0.13, 51.51] }, properties: { name: 'London', temp: 10, condition: 'Rainy 🌧️', humidity: 80, best: 'Jun–Aug', season: 'Oceanic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.01, 40.71] }, properties: { name: 'New York', temp: 14, condition: 'Variable 🌤️', humidity: 62, best: 'May–Jun, Sep–Oct', season: 'Temperate' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Sydney', temp: 22, condition: 'Sunny ☀️', humidity: 65, best: 'Sep–Nov, Mar–May', season: 'Temperate' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [174.76, -36.85] }, properties: { name: 'Auckland', temp: 16, condition: 'Mild 🌤️', humidity: 72, best: 'Dec–Feb', season: 'Oceanic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-7.98, 31.63] }, properties: { name: 'Marrakech', temp: 26, condition: 'Sunny ☀️', humidity: 38, best: 'Mar–May, Sep–Nov', season: 'Desert' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [36.82, -1.29] }, properties: { name: 'Nairobi', temp: 20, condition: 'Pleasant 🌤️', humidity: 60, best: 'Jun–Oct', season: 'Highland' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-77.04, -12.05] }, properties: { name: 'Lima', temp: 18, condition: 'Overcast 🌥️', humidity: 78, best: 'Dec–Apr', season: 'Desert Coast' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-99.13, 19.43] }, properties: { name: 'Mexico City', temp: 18, condition: 'Pleasant 🌤️', humidity: 55, best: 'Nov–Apr', season: 'Highland' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio', temp: 28, condition: 'Hot & Humid ☀️', humidity: 74, best: 'Apr–Jun', season: 'Tropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [72.88, 19.08] }, properties: { name: 'Mumbai', temp: 30, condition: 'Hot & Humid ☀️', humidity: 80, best: 'Nov–Feb', season: 'Tropical' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', temp: 35, condition: 'Very Hot ☀️', humidity: 55, best: 'Nov–Mar', season: 'Desert' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-79.38, 43.65] }, properties: { name: 'Toronto', temp: 8, condition: 'Cold ❄️', humidity: 68, best: 'Jun–Sep', season: 'Continental' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Berlin', temp: 10, condition: 'Mild 🌥️', humidity: 70, best: 'May–Sep', season: 'Temperate' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [4.90, 52.37] }, properties: { name: 'Amsterdam', temp: 11, condition: 'Rainy 🌧️', humidity: 78, best: 'Jun–Aug', season: 'Oceanic' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [14.42, 50.09] }, properties: { name: 'Prague', temp: 10, condition: 'Variable 🌤️', humidity: 68, best: 'May–Sep', season: 'Temperate' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.09, 42.65] }, properties: { name: 'Dubrovnik', temp: 22, condition: 'Sunny ☀️', humidity: 55, best: 'Jun–Sep', season: 'Mediterranean' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.98, 41.01] }, properties: { name: 'Istanbul', temp: 16, condition: 'Mild 🌤️', humidity: 68, best: 'Apr–Jun, Sep–Oct', season: 'Mediterranean' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.42, -33.92] }, properties: { name: 'Cape Town', temp: 17, condition: 'Pleasant 🌤️', humidity: 60, best: 'Nov–Apr', season: 'Mediterranean' } },
    ],
};
