// Simulated live weather conditions (in production, replace with OpenWeatherMap / Tomorrow.io API)
export const LIVE_WEATHER_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [100.50, 13.76] }, properties: { name: 'Bangkok', temp: 36, feels_like: 42, condition: 'Sunny', wind: 12, uv: 9, icon: '☀️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [139.69, 35.69] }, properties: { name: 'Tokyo', temp: 18, feels_like: 17, condition: 'Partly Cloudy', wind: 20, uv: 5, icon: '⛅', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [115.09, -8.34] }, properties: { name: 'Bali', temp: 29, feels_like: 35, condition: 'Thunderstorm', wind: 35, uv: 4, icon: '⛈️', alert: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [105.83, 21.03] }, properties: { name: 'Hanoi', temp: 26, feels_like: 29, condition: 'Hazy', wind: 8, uv: 6, icon: '🌫️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-9.14, 38.72] }, properties: { name: 'Lisbon', temp: 22, feels_like: 22, condition: 'Sunny', wind: 18, uv: 7, icon: '☀️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [103.82, 1.35] }, properties: { name: 'Singapore', temp: 31, feels_like: 38, condition: 'Humid & Sunny', wind: 10, uv: 8, icon: '🌤️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-21.93, 64.13] }, properties: { name: 'Reykjavik', temp: 6, feels_like: 2, condition: 'Windy', wind: 55, uv: 2, icon: '💨', alert: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-3.70, 40.42] }, properties: { name: 'Madrid', temp: 20, feels_like: 19, condition: 'Clear', wind: 14, uv: 7, icon: '☀️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [12.50, 41.90] }, properties: { name: 'Rome', temp: 24, feels_like: 24, condition: 'Partly Cloudy', wind: 16, uv: 7, icon: '⛅', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [23.73, 37.98] }, properties: { name: 'Athens', temp: 28, feels_like: 30, condition: 'Sunny', wind: 12, uv: 8, icon: '☀️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [2.35, 48.86] }, properties: { name: 'Paris', temp: 14, feels_like: 12, condition: 'Rainy', wind: 22, uv: 2, icon: '🌧️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-0.13, 51.51] }, properties: { name: 'London', temp: 12, feels_like: 9, condition: 'Drizzle', wind: 28, uv: 2, icon: '🌦️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-74.01, 40.71] }, properties: { name: 'New York', temp: 16, feels_like: 14, condition: 'Mostly Cloudy', wind: 24, uv: 4, icon: '☁️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [151.21, -33.87] }, properties: { name: 'Sydney', temp: 20, feels_like: 19, condition: 'Clear', wind: 20, uv: 5, icon: '☀️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-7.98, 31.63] }, properties: { name: 'Marrakech', temp: 32, feels_like: 30, condition: 'Sunny', wind: 9, uv: 9, icon: '☀️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [36.82, -1.29] }, properties: { name: 'Nairobi', temp: 21, feels_like: 20, condition: 'Partly Cloudy', wind: 14, uv: 6, icon: '⛅', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-43.17, -22.91] }, properties: { name: 'Rio de Janeiro', temp: 30, feels_like: 36, condition: 'Hot & Humid', wind: 15, uv: 8, icon: '🌡️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [72.88, 19.08] }, properties: { name: 'Mumbai', temp: 33, feels_like: 40, condition: 'Muggy', wind: 18, uv: 7, icon: '🌊', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [55.27, 25.20] }, properties: { name: 'Dubai', temp: 41, feels_like: 46, condition: 'Extreme Heat', wind: 8, uv: 11, icon: '🔆', alert: true } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-79.38, 43.65] }, properties: { name: 'Toronto', temp: 5, feels_like: 1, condition: 'Cold & Cloudy', wind: 30, uv: 2, icon: '❄️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [13.41, 52.52] }, properties: { name: 'Berlin', temp: 11, feels_like: 8, condition: 'Overcast', wind: 26, uv: 3, icon: '☁️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [4.90, 52.37] }, properties: { name: 'Amsterdam', temp: 10, feels_like: 7, condition: 'Rainy', wind: 32, uv: 2, icon: '🌧️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [14.42, 50.09] }, properties: { name: 'Prague', temp: 9, feels_like: 6, condition: 'Cloudy', wind: 20, uv: 3, icon: '⛅', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [28.98, 41.01] }, properties: { name: 'Istanbul', temp: 19, feels_like: 18, condition: 'Mild & Cloudy', wind: 18, uv: 5, icon: '🌥️', alert: false } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [18.42, -33.92] }, properties: { name: 'Cape Town', temp: 18, feels_like: 16, condition: 'Windy', wind: 45, uv: 5, icon: '💨', alert: false } },
    ],
};
