export const ADVENTURE_GEOJSON = {
    type: 'FeatureCollection' as const,
    features: [
        { type: 'Feature', geometry: { type: 'Point', coordinates: [83.99, 28.00] }, properties: { name: 'Nepal (Everest)', activity: 'Trekking', difficulty: 'Extreme', rating: 9.9, season: 'Mar–May, Sep–Nov', duration: '14–21 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-68.88, -32.65] }, properties: { name: 'Patagonia', activity: 'Hiking & Climbing', difficulty: 'Hard', rating: 9.7, season: 'Nov–Mar', duration: '7–14 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-3.24, -60.02] }, properties: { name: 'Amazon (Manaus)', activity: 'Jungle Expedition', difficulty: 'Hard', rating: 9.5, season: 'Jun–Nov', duration: '5–10 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [37.36, -3.07] }, properties: { name: 'Mt Kilimanjaro', activity: 'Climbing', difficulty: 'Hard', rating: 9.6, season: 'Jan–Mar, Jun–Oct', duration: '6–9 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [172.47, -43.73] }, properties: { name: 'Queenstown NZ', activity: 'Bungee & Skydive', difficulty: 'Medium', rating: 9.8, season: 'Year-round', duration: '1–3 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-156.74, 20.26] }, properties: { name: 'Maui Hawaii', activity: 'Surfing & Diving', difficulty: 'Medium', rating: 9.5, season: 'Apr–Oct', duration: '3–7 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [34.77, 29.53] }, properties: { name: 'Red Sea (Dahab)', activity: 'Scuba Diving', difficulty: 'Easy', rating: 9.4, season: 'Year-round', duration: '3–7 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-117.13, 36.49] }, properties: { name: 'Death Valley', activity: 'Desert Trek', difficulty: 'Hard', rating: 8.8, season: 'Oct–Apr', duration: '2–5 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [138.73, -8.60] }, properties: { name: 'Papua New Guinea', activity: 'Kokoda Track', difficulty: 'Extreme', rating: 9.3, season: 'Apr–Nov', duration: '8–12 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [98.55, 18.77] }, properties: { name: 'Chiang Mai', activity: 'Zip-lining & Rafting', difficulty: 'Easy', rating: 9.0, season: 'Nov–Apr', duration: '1–2 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-105.09, 40.37] }, properties: { name: 'Colorado Rockies', activity: 'Skiing & Snowboarding', difficulty: 'Medium', rating: 9.4, season: 'Dec–Apr', duration: '3–7 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [15.62, 78.23] }, properties: { name: 'Svalbard', activity: 'Arctic Expedition', difficulty: 'Hard', rating: 9.6, season: 'Feb–Apr, Jun–Aug', duration: '5–10 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-70.93, -53.16] }, properties: { name: 'Torres del Paine', activity: 'W-Trek', difficulty: 'Medium', rating: 9.7, season: 'Oct–Apr', duration: '4–8 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-73.98, -13.16] }, properties: { name: 'Machu Picchu', activity: 'Inca Trail', difficulty: 'Medium', rating: 9.8, season: 'Apr–Oct', duration: '4 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [31.13, -17.92] }, properties: { name: 'Victoria Falls', activity: 'White Water Rafting', difficulty: 'Hard', rating: 9.5, season: 'Aug–Dec', duration: '1–3 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-16.53, 28.40] }, properties: { name: 'Tenerife', activity: 'Mt Teide Climbing', difficulty: 'Medium', rating: 9.0, season: 'Apr–Oct', duration: '1–2 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [119.43, -8.65] }, properties: { name: 'Komodo', activity: 'Diving & Trekking', difficulty: 'Medium', rating: 9.3, season: 'Apr–Dec', duration: '3–5 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [-21.93, 64.13] }, properties: { name: 'Iceland', activity: 'Glacier Hike & Volcano', difficulty: 'Medium', rating: 9.6, season: 'Jun–Aug', duration: '5–10 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [47.27, 12.42] }, properties: { name: 'Djibouti', activity: 'Freediving', difficulty: 'Medium', rating: 9.1, season: 'Oct–May', duration: '3–7 days' } },
        { type: 'Feature', geometry: { type: 'Point', coordinates: [90.43, 27.46] }, properties: { name: 'Bhutan', activity: 'High-altitude Trekking', difficulty: 'Hard', rating: 9.5, season: 'Mar–May, Sep–Nov', duration: '7–14 days' } },
    ],
};
